---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午5:50
---

local function max(a,b)
    local temp = nil
    if a > b then
        temp = a
    else
        temp = b
    end
    return temp
end

local m = max(1,4)
print(m)


local function emptyParameter()
    print(" no parameter")
end

emptyParameter()


--- 由于函数定义等价于变量赋值，我们也可以把函数名替换为某个 Lua 表的某个字段，例如
local foo = {"bar=","aa"}
foo.bar = function(a,b,c)
    print("body",a,b,c)
    return a + b + c
end

local fn_a = foo.bar(1,2,3)
print(fn_a)



