---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午5:50
---

--- Lua 函数的参数大部分是按值传递的。值传递就是调用函数时，实参把它的值通过赋值运算传递给形参，然后形参的改变和实参就没有关系了。在这个过程中，实参是通过它在参数表中的位置与形参匹配起来的。
local function swap(a,b)
    local temp = a
    a = b
    b = temp
    print("swap ",a,b)
end

local x = "hello"
local y = 20
print(x,y)
swap(x,y)
print(x,y)


print("------------change 1--------------")

local function change(args)
    args.width = args.width * 2
    args.height = args.height * 2
    return  args
end


local rectangle = {width = 20,height=15}
print("before",rectangle.width,rectangle.height)
rectangle = change(rectangle)
print("after",rectangle.width,rectangle.height)


print("------------change 2--------------")

local rectangle2 = {width = 10,height=20}
local function change2(args)
    args.width = args.width * 2
    args.height = args.height * 2
end
print("before 2",rectangle2.width,rectangle2.height)
change2(rectangle2)
print("after 2",rectangle2.width,rectangle2.height)
