---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午3:53
---

print(type("hello word"))

print(type(print))

print(type(true))

print(type(360.0))

print(type(nil))

--- nil
local num
print(num)

num = 100
print(num)

--- boolean
--- Lua中除nil 和 false 为假 其余均为真
local a = true
local b = 0
local c = nil


if b then
    print("b 为真")
else
    print("not b")
end

if c then
    print("c 为假")
else
    print("not c")
end

if a then
    print("a 为真")
else
    print("not a")
end


--- num
---
local order = 3.99
local score = 98.01
print(math.floor(order))
print(math.ceil(score))

print(order + score)

print(9223372036854775807 - 1)  -->output:9223372036854775806LL

--- string
local str_a = 'hello'
local str_b = "hello"
local str_c = [["add\name",'hello']]
local str_d = [=[string hava a [[]].]=]

print(str_a)
print(str_b)
print(str_c)
print(str_d)

--- table
---

local crop = {
    web = "www.baidu.com",
    telephone = "1234567",
    staff = {"jack","scort","Gray"},
    100879,
    100191,
    [10] = 360,
    ['city'] = "beijing"
}

print(crop.web)
print(crop["telephone"])
print(crop[2])
print(crop["city"])
print(crop.staff[1])
print(crop[10])


--- funciton
---
print("-------------------")

local function foo()
    print("int the function")
    local x = 10
    local y = 20
    local x = 20
    return x + y
end

local a = foo
print(a())

local b = foo()
print(b)


















