---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 上午12:10
---

local file = io.input("test1")

repeat
    local line = file.read(file)
    if  nil == line then
        break
    end
    print(line)
until(false)

io.close(file)                  -- 关闭文件


file = io.open("test1", "a+")   -- 使用 io.open() 函数，以添加模式打开文件
io.output(file)                     -- 使用 io.output() 函数，设置默认输出文件
io.write("\nhello world 222")           -- 使用 io.write() 函数，把内容写到文件
io.close(file)


print("-----------------------")

file = io.open("test1", "r")    -- 使用 io.open() 函数，以只读模式打开文件
for line in file:lines() do         -- 使用 file:lines() 函数逐行读取文件
    print(line)
end
file:close()

print("-------------------------------")
-- 在 test2.txt 文件的最后添加一行 "hello world"
file = io.open("test1", "a")  -- 使用 io.open() 函数，以添加模式打开文件
print(io.type(file))
file:write("\nhello world ddddd ")       -- 使用 file:write() 函数，在文件末尾追加内容
file:flush()
file:close()


print("-------------------------------")
local lines = io.lines("test3.txt");
print(type(lines))
print(io.type(lines))

for line in lines do
    print(line)
end

print("-------------------------------")





