---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午5:10
---
for i = 1, 10, 2 do
    print(i)
end

for i = 1, 10, 3 do
    print(i)
end

local a = {"a", "b", "c", "d"}

for i, v in ipairs(a) do
    print("index ",i," value:",v)
end
print("拼接",table.concat(a))


local days = {
    "Sunday", "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday"
}

local revDays = {}
for i, v in pairs(days) do
    revDays[v] = i
end

for i, v in pairs(revDays) do
    print("index ",i , " value ",v)
end












