---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午11:07
---

local color={first="red", "blue", third="green", "yellow"}
print(color["first"])
print(color[1])
print(color.third)
print(color[2])
print(color[3])
print(#color)

color[#color + 1] = "pink"
print(color[3])
print(#color)


--- 字符串的长度是是字节数
local val = "hello word"
print(#val)

--- 这也就说明对于有“空洞”的情况，table 的长度存在一定的 不可确定性。
local tblTest1 = { 1, a = 2, 3 }
print("len = " .. table.getn(tblTest1))

local tblTest2 = { 1, nil }
print("Test2 " .. table.getn(tblTest2))

local tblTest3 = { 1, nil, 2 }
print("Test3 " .. table.getn(tblTest3))

local tblTest4 = { 1, nil, 2, nil }
print("Test4 " .. table.getn(tblTest4))


local tblTest5 = { 1, nil, 2, nil, 3, nil }
print("Test5 " .. table.getn(tblTest5))

local tblTest6 = { 1, 2, 3 }
print("Test6 " .. table.getn(tblTest6))

table.remove(tblTest6,2)
print(table.getn(tblTest6))
print(table.concat(tblTest6,","))



local a = {1, 3, 5, "hello" }
print(table.concat(a))
print(table.concat(a, "|"))         -- output: 1|3|5|hello
print(table.concat(a, " ", 4, 2))   -- output:
print(table.concat(a, " ", 2, 4))   -- output:

--- 在（数组型）表 table 的 pos 索引位置插入 value，其它元素向后移动到空的地方。pos 的默认值是表的长度加一，即默认是插在表的最后。
--- table.insert (table, [pos ,] value)

local b = {1, 3, 5, "hello" }
table.insert(b,"word")
print(table.concat(b,"|"))

table.insert(b,1,0)
print(table.concat(b,"-"))

--- table.maxn (table)


local c = {1, 3, 5, "hello" }
print(#c)
print(table.maxn(c))

c[10] = "word"
print(table.maxn(c))

--- table.remove (table [, pos])
local a = { 1, 2, 3, 4}
print(table.remove(a, 1)) --删除速索引为1的元素
print(a[1], a[2], a[3], a[4])

print(table.remove(a))   --删除最后一个元素
print(a[1], a[2], a[3], a[4])

--- table.sort (table [, comp])
local s1 = { -1, 9, 3, 2,3}
table.sort(s1)
print(table.concat(s1," "))

local function compare(x, y) --从大到小排序
    return x > y         --如果第一个参数大于第二个就返回true，否则返回false
end

table.sort(s1,compare)
print(table.concat(s1," "))

--- table.new
--- table.clear








