---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午10:47
---

local _M = {}

function _M.greeting(name)
    local word = get_name()

    getmetatable()

    return "hi," .. name .. " " .. word
end

function get_name()
    return " Luckly"
end

return _M