---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 上午12:10
---

---  创建文件每次重新开始写入 写模式 w - 创建文件
--[[
print("write starting")
local file = io.open("test3.txt","w")
file:write("\n how")
file:write("\n are")
file:write("\n you")
file:close()
print("write success")]]


--- 添加模式 a  文件如果存在保留之前的内容在文件末添加，如果文件不存在则创建文件并写入
--[[
print("write starting")
local file = io.open("test4.txt","a")
file:write("how")
file:write("\n are")
file:write("\n you")
file:close()]]


--- w+ 更新模式 清除之前的数据  - 创建文件
--[[
local file = io.open("test4.txt","w+")
file:write("how")
file:close()]]

--- "r+"  清除数据重新写入
--[[local file = io.open("test4.txt","r+")
file:write("\n are")
file:write("\n 222")]]

local file = io.open("test4.txt","a")
file:write("\n are")
file:write("\n 222")
file:close()