---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午6:41
---

local s, e = string.find("hello world", "llo")
print("s,e",s,e)


local function swap(a,b)
    return b,a
end

local a , b = swap(1,5)
print("a,b",a,b)


local function init()
    return 1,"lua"
end


local init_value = init()
print("init_value",init_value)

local v1,v2,v3 = init()
print("v1,v2,v3",v1,v2,v3)




