---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午10:51
---

local my_module = require("lua-modle-m")

local word = my_module.greeting("turbo")


print(word)

