---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/3 下午5:01
---

local x = 10
if x > 10 then
    print(1)
elseif x < 10 then
    print(2)
else
    print(3)
end

if nil then
    print("nil")
else
    print("ele nil")
end



--- while

local a = 10
while a > 5 do
    print(a)
    a = a - 1
end


local t = {1, 3, 5, 8, 11, 18, 21}
local i
for i, v in ipairs(t) do
    print(i .. "--" .. v)
    if v > 5 then
        break
    end
end

--- repeat
local x = 10
repeat
    print(x)
until false



