---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 下午2:35
---
local _M = {}

local mt = {__index = _M}

function _M.upper(s)
    return string.upper(s)
end

return _M



