---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 下午3:39
---



--- 调用代码前先定义函数

local a = 100;

local function add(b)
    return a + b
end

local c = add(100)

print(c)


--- 为什么放在调用后面就找不到呢？原因是 Lua 里的 function 定义本质上是变量赋值，即
--- 因此在函数定义之前使用函数相当于在变量赋值之前使用变量，Lua 世界对于没有赋值的变量，默认都是 nil，所以这里也就产生了一个 nil 的错误。
local add1 = function(b)
    return b + a
end





