---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 下午2:47
---

function newAccount(initBalance)
    local self = {balance = initBalance}
    local withdraw = function(v)
        self.balance = self.balance - v
    end

    local deposit = function(v)
        self.balance = self.balance + v
    end

    local getBalance = function()
        return self.balance
    end

    return {
        withdraw = withdraw,
        deposit = deposit,
        getBalance = getBalance
    }
end


a = newAccount(100)
a.deposit(50)
a.withdraw(10)
print(a.getBalance())

function isTableEmpty(t)
    return t == nil or next(t) == nil
end

if a ~= nil and a.getBalance ~= nil then
    print("字段不为空")
end
