---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 下午2:11
---

local _M = {_VERSION = "0.1"}

local mt = {__index = _M}

function _M.deposit(self,v)
    self.balance = self.balance + v
end

function _M.withdraw(self,v)
    if self.balance > v then
        self.balance = self.balance - v
    else
        error("insufficient funds")
    end
end

function _M.new(self,balance)
    balance = balance or 0
    return setmetatable({balance = balance},mt)
end

return _M


--- 当 lua_code_cache on 开启时，require 加载的模块是会被缓存下来的
--- local square = require "square"
--- 直到被显式地调用如下语句 卸载某个模块
--- package.loaded["square"] = nil
