---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/4 下午2:19
---

--[[local account = require("./heigh/lua-class-pojo")
local a = account:new();
a:deposit(100)
print(a.balance)

local b = account:new()
b:deposit(50)
print(b.balance)]]


local s_more = require("./heigh/lua-extend-more")
print(s_more:lower("HELLO"))
print(s_more.upper("hello"))
